### ISSUE TITLE
How much GPU memory is needed to run PoseCNN?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [yuxng/PoseCNN#65]
I get the message that I am running out of memory on my GPU and I was wondering if it is worth trying to get it all to fit into 4GB or I would need a cluster with xx GB of memory to run it anyway and to not bother with a small laptop?

I tried reducing the kThreadsPerBlock to 512 like mentioned somewhere else but this still was not enough. Is there a minimum size this kThreadsPerBlock can be set to? Would it work with a value of 1?

**Comment by Kaju-Bubanja** [comment]
I am not sure how much is needed at minimum, but I could run the model with 12GB and batch size 1

**Comment by briliantnugraha** [comment]
Hi @Kaju-Bubanja , could I know how do you solve the problem? is it by changing your GPU with the one that has 12GB of memory? Thanks in advance!

**Comment by Kaju-Bubanja** [comment]
I guess there are other ways, but yes I could only resolve it by using a gpu with 12GB of memory

**Comment by hamza-04** [comment]
Hi @Kaju-Bubanja , could you please give more details about how to change the size batch , i'm new in using tensorflow and i actually succeeded in compiling all steps of posecnn project, but now i'm in the last step of the training via : 
# training
./experiments/scripts/lov_color_2d_train.sh  0

But i sadly got exhausted memory .  

i'm using ubuntu 16.04 
cuda 8 ,
gtx 1070 ( 8 go )
tensorflow-gpu with pip

**Comment by briliantnugraha** [comment]
Hi @hamza-04, you could try 2 things (which is working for me):
1. Reduce batch size:
- Open PoseCNN\experiments\cfgs\lov_color_2d.yml
- Change the "IMS_PER_BATCH" option from 2 to 1

2. Reduce KThreadPerBlocks from 1024 to 512 as suggested by @Kaju-Bubanja in all files (use vscode or other editors for faster edit)

**Comment by briliantnugraha** [comment]
Thanks for the reply @Kaju-Bubanja, I and my colleague have been a lot through the process of Pose CNN. But in the training, we still met with the issue where the "loss_pose" will go OOM if this condition "if(cls == gt_id && batch_index == gt_batch)" is disabled (the code always go to the operation in the former condition) in hough_voting_gpu_op.cu.cc. Do you encounter the similar issue like us? Or could you share some exp on the training of PoseCNN (I already checked your repo though, but there is not an issue like what is happening in our case).

Total class: 2 (background 1, and object 1)
GPU: was GTX 1080 TI, currently TITAN V (OOM in this condition)
RAM: 32 GB
OS: Ubuntu 16.04
Thanks for your help in advance!

**Comment by Nathan-81** [comment]
@briliantnugraha @Kaju-Bubanja  Hi !
I had the same problem (Nvidia RTX 2070 GB) and thanks to your answers I was able to start training the network but when I reduced the IMS_PER_BATCH from 2 to 1 my training stop at iteration 224 with this error : 

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 140) > this->size() (which is 0)
./experiments/scripts/lov_color_2d_train.sh: line 23:  1920 Aborted                 (core dumped) ./tools/train_net.py --gpu 0 --network vgg16_convs --weights data/imagenet_models/vgg16.npy --imdb lov_train --cfg experiments/cfgs/lov_color_2d.yml --cad data/LOV/models.txt --pose data/LOV/poses.txt --iters 16000

PS : I only train one model (so 2 classes with the background) in order to save memory.

If I let the IMS_PER_BATCH to 2 with only one model the training stop at 2847 iterations with the same error.

Had you encountered this error too ?
